{
 "title": "Yoga Companion",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User Feedback",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\r\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\r\nFROM feedback\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\n"
    }
   ]
  },
  {
   "title": "Relevancy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN relevance IN ('PARTLY_RELEVANT', 'RELEVANT') THEN 'RELEVANT'\r\n    ELSE 'NON_RELEVANT'\r\n  END as relevance_group,\r\n  COUNT(*) as count\r\nFROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY relevance_group\r\n"
    }
   ]
  },
  {
   "title": "OpenAI cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  openai_cost\r\nFROM conversations\r\nWHERE openai_cost > 0\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  total_tokens\r\nFROM conversations\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  question,\r\n  answer,\r\n  CASE \r\n    WHEN relevance IN ('PARTLY_RELEVANT', 'RELEVANT') THEN 'RELEVANT'\r\n    ELSE 'NON_RELEVANT'\r\n  END as relevance\r\nFROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY timestamp DESC\r\nLIMIT 5\r\n"
    }
   ]
  }
 ]
}